#!/usr/bin/perl

print("瑞哥版权所有，更多资料请添加微信marey_marey111\n");
print("瑞哥版权所有，跟多资料请参阅视频：https://www.youtube.com/channel/UCH7MTlHOfCjEa5yWII5P5rg?view_as=subscriber\n");

# check input params
die "usage: dengdeng_comp9021_test skip_line_number python_file_name test_case_filename\n" if @ARGV !=3;

# skip_line_number
$skip_line_number = shift;

$python_file_name = shift;
# check exists
die "legit-dengdeng_comp9021_test: error: $python_file_name not exists!\n" if ! -e $python_file_name;

$test_file_name = shift;
# check exists
die "legit-dengdeng_comp9021_test: error: $test_file_name not exists!\n" if ! -e $test_file_name;

open my $in, '<', $test_file_name or die "$test_file_name 文件无法打开\n";
my @lines = <$in>;
close $in;

my $command = "";
my @exp_results = ();
foreach my $line (@lines){
		chomp $line;

		if ( $line =~ /TEST \d+ BEGIN/ ) {
		    print("$line\n");
		    @exp_results = ();
		    next;
		}

        if ($line =~ /TEST \d+ END/ ) {
            $command =~ s/\|.*/| python3 $python_file_name/g;

            my @real_results = (`$command`);
            my $org_real = join("", @real_results);

            @real_results = split(/:/,$org_real,$skip_line_number);

            while ($skip_line_number > 0) {
                shift @real_results;
                $skip_line_number -= 1;
            }

            $org_real = join("", @real_results);

            my $real = join( "", @real_results);
            my $org_exp = join( "\n", @exp_results);

            shift @exp_results;
            shift @exp_results;

            my $exp = join( "\n", @exp_results);
            $exp =~ s/\s+$//g;
            $real =~ s/\s+$//g;

            if ("$real" eq "$exp"){
                print("==============Test Pass==========\n");
            }else {

                print("COMMADN:\n$command\n");
                print("==============Test Error==========\n");
                print("==============Your Output=========\n");
                print("$real\n");
                print("==============Expect Output=======\n");
                print("$exp\n");
            }
            print("$line\n");
            next;
        }

        if ($line =~ /\$ /) {
            $line =~ s/\$ //g;
            $command = $line;
            next;
        }

        push @exp_results,$line
}